# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: containerd/api/services/namespaces/v1/namespace.proto for package 'containerd.services.namespaces.v1'
# Original file comments:
#
# Copyright The containerd Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'grpc'
require_relative 'namespace_pb'

module Containerd
  module Services
    module Namespaces
      module V1
        module Namespaces
          # Namespaces provides the ability to manipulate containerd namespaces.
          #
          # All objects in the system are required to be a member of a namespace. If a
          # namespace is deleted, all objects, including containers, images and
          # snapshots, will be deleted, as well.
          #
          # Unless otherwise noted, operations in containerd apply only to the namespace
          # supplied per request.
          #
          # I hope this goes without saying, but namespaces are themselves NOT
          # namespaced.
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'containerd.services.namespaces.v1.Namespaces'

            rpc :Get, ::Containerd::Services::Namespaces::V1::GetNamespaceRequest, ::Containerd::Services::Namespaces::V1::GetNamespaceResponse
            rpc :List, ::Containerd::Services::Namespaces::V1::ListNamespacesRequest, ::Containerd::Services::Namespaces::V1::ListNamespacesResponse
            rpc :Create, ::Containerd::Services::Namespaces::V1::CreateNamespaceRequest, ::Containerd::Services::Namespaces::V1::CreateNamespaceResponse
            rpc :Update, ::Containerd::Services::Namespaces::V1::UpdateNamespaceRequest, ::Containerd::Services::Namespaces::V1::UpdateNamespaceResponse
            rpc :Delete, ::Containerd::Services::Namespaces::V1::DeleteNamespaceRequest, ::Google::Protobuf::Empty
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
