# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: containerd/api/services/containers/v1/containers.proto for package 'containerd.services.containers.v1'
# Original file comments:
#
# Copyright The containerd Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'grpc'
require 'containerd/api/services/containers/v1/containers_pb'

module Containerd
  module Services
    module Containers
      module V1
        module Containers
          # Containers provides metadata storage for containers used in the execution
          # service.
          #
          # The objects here provide an state-independent view of containers for use in
          # management and resource pinning. From that perspective, containers do not
          # have a "state" but rather this is the set of resources that will be
          # considered in use by the container.
          #
          # From the perspective of the execution service, these objects represent the
          # base parameters for creating a container process.
          #
          # In general, when looking to add fields for this type, first ask yourself
          # whether or not the function of the field has to do with runtime execution or
          # is invariant of the runtime state of the container. If it has to do with
          # runtime, or changes as the "container" is started and stops, it probably
          # doesn't belong on this object.
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'containerd.services.containers.v1.Containers'

            rpc :Get, ::Containerd::Services::Containers::V1::GetContainerRequest, ::Containerd::Services::Containers::V1::GetContainerResponse
            rpc :List, ::Containerd::Services::Containers::V1::ListContainersRequest, ::Containerd::Services::Containers::V1::ListContainersResponse
            rpc :ListStream, ::Containerd::Services::Containers::V1::ListContainersRequest, stream(::Containerd::Services::Containers::V1::ListContainerMessage)
            rpc :Create, ::Containerd::Services::Containers::V1::CreateContainerRequest, ::Containerd::Services::Containers::V1::CreateContainerResponse
            rpc :Update, ::Containerd::Services::Containers::V1::UpdateContainerRequest, ::Containerd::Services::Containers::V1::UpdateContainerResponse
            rpc :Delete, ::Containerd::Services::Containers::V1::DeleteContainerRequest, ::Google::Protobuf::Empty
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
