# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/containerd/containerd/api/types/platform.proto

require 'google/protobuf'


descriptor_data = "\n9github.com/containerd/containerd/api/types/platform.proto\x12\x10\x63ontainerd.types\"Q\n\x08Platform\x12\n\n\x02os\x18\x01 \x01(\t\x12\x14\n\x0c\x61rchitecture\x18\x02 \x01(\t\x12\x0f\n\x07variant\x18\x03 \x01(\t\x12\x12\n\nos_version\x18\x04 \x01(\tB2Z0github.com/containerd/containerd/api/types;typesb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Containerd
  module Types
    Platform = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("containerd.types.Platform").msgclass
  end
end
