# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/containerd/containerd/api/types/transfer/imagestore.proto

require 'google/protobuf'

require 'github.com/containerd/containerd/api/types/platform_pb'

descriptor_data = "\nDgithub.com/containerd/containerd/api/types/transfer/imagestore.proto\x12\x19\x63ontainerd.types.transfer\x1a\x39github.com/containerd/containerd/api/types/platform.proto\"\xef\x02\n\nImageStore\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x41\n\x06labels\x18\x02 \x03(\x0b\x32\x31.containerd.types.transfer.ImageStore.LabelsEntry\x12-\n\tplatforms\x18\x03 \x03(\x0b\x32\x1a.containerd.types.Platform\x12\x14\n\x0c\x61ll_metadata\x18\x04 \x01(\x08\x12\x16\n\x0emanifest_limit\x18\x05 \x01(\r\x12\x43\n\x10\x65xtra_references\x18\x06 \x03(\x0b\x32).containerd.types.transfer.ImageReference\x12?\n\x07unpacks\x18\n \x03(\x0b\x32..containerd.types.transfer.UnpackConfiguration\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"X\n\x13UnpackConfiguration\x12,\n\x08platform\x18\x01 \x01(\x0b\x32\x1a.containerd.types.Platform\x12\x13\n\x0bsnapshotter\x18\x02 \x01(\t\"y\n\x0eImageReference\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tis_prefix\x18\x02 \x01(\x08\x12\x17\n\x0f\x61llow_overwrite\x18\x03 \x01(\x08\x12\x12\n\nadd_digest\x18\x04 \x01(\x08\x12\x19\n\x11skip_named_digest\x18\x05 \x01(\x08\x42\x35Z3github.com/containerd/containerd/api/types/transferb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Containerd
  module Types
    module Transfer
      ImageStore = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("containerd.types.transfer.ImageStore").msgclass
      UnpackConfiguration = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("containerd.types.transfer.UnpackConfiguration").msgclass
      ImageReference = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("containerd.types.transfer.ImageReference").msgclass
    end
  end
end
