# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/containerd/containerd/api/types/transfer/registry.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'


descriptor_data = "\nBgithub.com/containerd/containerd/api/types/transfer/registry.proto\x12\x19\x63ontainerd.types.transfer\x1a\x1fgoogle/protobuf/timestamp.proto\"_\n\x0bOCIRegistry\x12\x11\n\treference\x18\x01 \x01(\t\x12=\n\x08resolver\x18\x02 \x01(\x0b\x32+.containerd.types.transfer.RegistryResolver\"\x9b\x02\n\x10RegistryResolver\x12\x13\n\x0b\x61uth_stream\x18\x01 \x01(\t\x12I\n\x07headers\x18\x02 \x03(\x0b\x32\x38.containerd.types.transfer.RegistryResolver.HeadersEntry\x12\x10\n\x08host_dir\x18\x03 \x01(\t\x12\x16\n\x0e\x64\x65\x66\x61ult_scheme\x18\x04 \x01(\t\x12\x38\n\nhttp_debug\x18\x05 \x01(\x0e\x32$.containerd.types.transfer.HTTPDebug\x12\x13\n\x0blogs_stream\x18\x06 \x01(\t\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"G\n\x0b\x41uthRequest\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x11\n\treference\x18\x02 \x01(\t\x12\x17\n\x0fwwwauthenticate\x18\x03 \x03(\t\"\x96\x01\n\x0c\x41uthResponse\x12\x35\n\x08\x61uthType\x18\x01 \x01(\x0e\x32#.containerd.types.transfer.AuthType\x12\x0e\n\x06secret\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12-\n\texpire_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*9\n\tHTTPDebug\x12\x0c\n\x08\x44ISABLED\x10\x00\x12\t\n\x05\x44\x45\x42UG\x10\x01\x12\t\n\x05TRACE\x10\x02\x12\x08\n\x04\x42OTH\x10\x03*>\n\x08\x41uthType\x12\x08\n\x04NONE\x10\x00\x12\x0f\n\x0b\x43REDENTIALS\x10\x01\x12\x0b\n\x07REFRESH\x10\x02\x12\n\n\x06HEADER\x10\x03\x42\x35Z3github.com/containerd/containerd/api/types/transferb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Containerd
  module Types
    module Transfer
      OCIRegistry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("containerd.types.transfer.OCIRegistry").msgclass
      RegistryResolver = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("containerd.types.transfer.RegistryResolver").msgclass
      AuthRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("containerd.types.transfer.AuthRequest").msgclass
      AuthResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("containerd.types.transfer.AuthResponse").msgclass
      HTTPDebug = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("containerd.types.transfer.HTTPDebug").enummodule
      AuthType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("containerd.types.transfer.AuthType").enummodule
    end
  end
end
