# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: github.com/containerd/containerd/api/services/transfer/v1/transfer.proto for package 'containerd.services.transfer.v1'
# Original file comments:
#
# Copyright The containerd Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'grpc'
require 'github.com/containerd/containerd/api/services/transfer/v1/transfer_pb'

module Containerd
  module Services
    module Transfer
      module V1
        module Transfer
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'containerd.services.transfer.v1.Transfer'

            rpc :Transfer, ::Containerd::Services::Transfer::V1::TransferRequest, ::Google::Protobuf::Empty
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
