# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/containerd/containerd/api/services/transfer/v1/transfer.proto

require 'google/protobuf'

require 'google/protobuf/any_pb'
require 'google/protobuf/empty_pb'


descriptor_data = "\nHgithub.com/containerd/containerd/api/services/transfer/v1/transfer.proto\x12\x1f\x63ontainerd.services.transfer.v1\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xa5\x01\n\x0fTransferRequest\x12$\n\x06source\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\x12)\n\x0b\x64\x65stination\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x41\n\x07options\x18\x03 \x01(\x0b\x32\x30.containerd.services.transfer.v1.TransferOptions\"*\n\x0fTransferOptions\x12\x17\n\x0fprogress_stream\x18\x01 \x01(\t2`\n\x08Transfer\x12T\n\x08Transfer\x12\x30.containerd.services.transfer.v1.TransferRequest\x1a\x16.google.protobuf.EmptyBDZBgithub.com/containerd/containerd/api/services/transfer/v1;transferb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Containerd
  module Services
    module Transfer
      module V1
        TransferRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("containerd.services.transfer.v1.TransferRequest").msgclass
        TransferOptions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("containerd.services.transfer.v1.TransferOptions").msgclass
      end
    end
  end
end
