# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: containerd/api/services/version/v1/version.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'


descriptor_data = "\n0containerd/api/services/version/v1/version.proto\x12\x1e\x63ontainerd.services.version.v1\x1a\x1bgoogle/protobuf/empty.proto\"4\n\x0fVersionResponse\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x10\n\x08revision\x18\x02 \x01(\t2]\n\x07Version\x12R\n\x07Version\x12\x16.google.protobuf.Empty\x1a/.containerd.services.version.v1.VersionResponseBBZ@github.com/containerd/containerd/api/services/version/v1;versionb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Containerd
  module Services
    module Version
      module V1
        VersionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("containerd.services.version.v1.VersionResponse").msgclass
      end
    end
  end
end
