# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: containerd/api/services/version/v1/version.proto for package 'containerd.services.version.v1'
# Original file comments:
#
# Copyright The containerd Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'grpc'
require_relative 'version_pb'

module Containerd
  module Services
    module Version
      module V1
        module Version
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'containerd.services.version.v1.Version'

            rpc :Version, ::Google::Protobuf::Empty, ::Containerd::Services::Version::V1::VersionResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
