# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: containerd/api/types/descriptor.proto

require 'google/protobuf'


descriptor_data = "\n%containerd/api/types/descriptor.proto\x12\x10\x63ontainerd.types\"\xb6\x01\n\nDescriptor\x12\x12\n\nmedia_type\x18\x01 \x01(\t\x12\x0e\n\x06\x64igest\x18\x02 \x01(\t\x12\x0c\n\x04size\x18\x03 \x01(\x03\x12\x42\n\x0b\x61nnotations\x18\x05 \x03(\x0b\x32-.containerd.types.Descriptor.AnnotationsEntry\x1a\x32\n\x10\x41nnotationsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x32Z0github.com/containerd/containerd/api/types;typesb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Containerd
  module Types
    Descriptor = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("containerd.types.Descriptor").msgclass
  end
end
