# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: containerd/api/services/images/v1/images.proto for package 'containerd.services.images.v1'
# Original file comments:
#
# Copyright The containerd Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'grpc'
require_relative 'images_pb'

module Containerd
  module Services
    module Images
      module V1
        module Images
          # Images is a service that allows one to register images with containerd.
          #
          # In containerd, an image is merely the mapping of a name to a content root,
          # described by a descriptor. The behavior and state of image is purely
          # dictated by the type of the descriptor.
          #
          # From the perspective of this service, these references are mostly shallow,
          # in that the existence of the required content won't be validated until
          # required by consuming services.
          #
          # As such, this can really be considered a "metadata service".
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'containerd.services.images.v1.Images'

            # Get returns an image by name.
            rpc :Get, ::Containerd::Services::Images::V1::GetImageRequest, ::Containerd::Services::Images::V1::GetImageResponse
            # List returns a list of all images known to containerd.
            rpc :List, ::Containerd::Services::Images::V1::ListImagesRequest, ::Containerd::Services::Images::V1::ListImagesResponse
            # Create an image record in the metadata store.
            #
            # The name of the image must be unique.
            rpc :Create, ::Containerd::Services::Images::V1::CreateImageRequest, ::Containerd::Services::Images::V1::CreateImageResponse
            # Update assigns the name to a given target image based on the provided
            # image.
            rpc :Update, ::Containerd::Services::Images::V1::UpdateImageRequest, ::Containerd::Services::Images::V1::UpdateImageResponse
            # Delete deletes the image by name.
            rpc :Delete, ::Containerd::Services::Images::V1::DeleteImageRequest, ::Google::Protobuf::Empty
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
